# Generated by Django 4.1.7 on 2023-03-26 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(blank=True, default='no_car.png', null=True, upload_to='covers', verbose_name='Virselis')),
                ('valstybinis_nr', models.CharField(max_length=12, verbose_name='Valstybinis numeris')),
                ('vin_code', models.CharField(max_length=20, verbose_name='VIN')),
                ('customer', models.CharField(max_length=100, verbose_name='Klientas')),
                ('description', tinymce.models.HTMLField(default='', verbose_name='Aprasymas')),
            ],
            options={
                'verbose_name': 'Car object',
                'verbose_name_plural': 'car object',
                'db_table': 'car',
                'ordering': ['customer', 'vin_code', 'customer'],
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marke', models.CharField(max_length=100, verbose_name='Marke')),
                ('model', models.CharField(max_length=100, verbose_name='Modelis')),
            ],
            options={
                'verbose_name': 'Car model',
                'verbose_name_plural': 'car model',
                'db_table': 'car_model',
                'ordering': ['marke', 'model'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('servis', models.CharField(blank=True, choices=[('p', 'Patvirtintas'), ('v', 'Vykdoma'), ('a', 'Atlikta'), ('t', 'Atsaukta')], default='p', max_length=50, verbose_name='Serviso pavadinimas')),
                ('car_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_service_app.car')),
                ('useris', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'order',
                'db_table': 'order',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Pavadinimas')),
            ],
            options={
                'verbose_name': 'Paslauga',
                'verbose_name_plural': 'Paslaugos',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuotrauka', models.ImageField(default='no_image.png', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserProfile',
                'verbose_name_plural': 'UserProfiliai',
            },
        ),
        migrations.CreateModel(
            name='Paslaugos_kaina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Kaina')),
                ('car_ids', models.ManyToManyField(to='car_service_app.carmodel')),
                ('service_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_service_app.service')),
            ],
            options={
                'verbose_name': 'Paslaugos kaina',
                'verbose_name_plural': 'Paslaugų kainos',
            },
        ),
        migrations.CreateModel(
            name='OrderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(max_length=2000, verbose_name='Atsiliepimas')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_service_app.order')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': "Comment's",
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=10, verbose_name='Kiekis')),
                ('price', models.CharField(max_length=10, verbose_name='Kaina')),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eilutes', to='car_service_app.order')),
                ('service_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_service_app.service')),
            ],
            options={
                'verbose_name': 'Order line',
                'verbose_name_plural': 'order line',
                'db_table': 'order_line',
                'ordering': ['quantity', 'price'],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='car_model_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_service_app.carmodel'),
        ),
    ]
