# Generated by Django 4.1.7 on 2023-03-30 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(blank=True, default='no_car.png', null=True, upload_to='covers', verbose_name='Cover')),
                ('valstybinis_nr', models.CharField(max_length=12, verbose_name='License plate')),
                ('vin_code', models.CharField(max_length=20, verbose_name='VIN code')),
                ('customer', models.CharField(max_length=100, verbose_name='Client')),
                ('description', tinymce.models.HTMLField(default='', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Car object',
                'verbose_name_plural': "Car object's",
                'db_table': 'car',
                'ordering': ['customer', 'vin_code', 'customer'],
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marke', models.CharField(max_length=100, verbose_name='Brand')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Car model',
                'verbose_name_plural': 'car model',
                'db_table': 'car_model',
                'ordering': ['marke', 'model'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('servis', models.CharField(blank=True, choices=[('p', 'Confirmed'), ('v', 'In progress'), ('a', 'Done'), ('t', 'Cancelled')], default='p', max_length=50, verbose_name='Service name')),
                ('car_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_service_app.car')),
                ('useris', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': "Order's",
                'db_table': 'order',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Name',
                'verbose_name_plural': "Name's",
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuotrauka', models.ImageField(default='no_image.png', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserProfile',
                'verbose_name_plural': "UserProfile's",
            },
        ),
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Price')),
                ('car_ids', models.ManyToManyField(to='car_service_app.carmodel')),
                ('service_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_service_app.service')),
            ],
            options={
                'verbose_name': 'Service price',
                'verbose_name_plural': 'Service price',
            },
        ),
        migrations.CreateModel(
            name='OrderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(max_length=2000, verbose_name='Comment')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_service_app.order')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': "Comment's",
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=10, verbose_name='Quantity')),
                ('price', models.CharField(max_length=10, verbose_name='Price')),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eilutes', to='car_service_app.order')),
                ('service_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_service_app.service')),
            ],
            options={
                'verbose_name': 'Order line',
                'verbose_name_plural': "Order line's",
                'db_table': 'order_line',
                'ordering': ['quantity', 'price'],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='car_model_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_service_app.carmodel'),
        ),
    ]
