# Generated by Django 4.1.7 on 2023-03-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service_app', '0003_alter_car_options_alter_carmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='servis',
            field=models.CharField(blank=True, choices=[('p', 'Patvirtintas'), ('v', 'Vykdoma'), ('a', 'Atlikta'), ('t', 'Atsaukta')], default='p', max_length=50, verbose_name='Serviso pavadinimas'),
        ),
    ]
