# Generated by Django 4.1.7 on 2023-03-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service_app', '0004_alter_order_servis'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers', verbose_name='Virselis'),
        ),
    ]
