# Generated by Django 4.1.7 on 2023-03-16 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car_service_app', '0005_car_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='useris',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='data',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data'),
        ),
    ]
