# Generated by Django 4.1.7 on 2023-03-16 18:52

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service_app', '0006_order_useris_alter_order_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=tinymce.models.HTMLField(default='', verbose_name='Aprasymas'),
        ),
    ]
