# Generated by Django 4.1.7 on 2023-03-22 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_service_app', '0008_orderreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderreview',
            options={'ordering': ['-date_created'], 'verbose_name': 'Comment', 'verbose_name_plural': "Comment's"},
        ),
        migrations.RemoveField(
            model_name='orderreview',
            name='car',
        ),
        migrations.AddField(
            model_name='orderreview',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_service_app.order'),
        ),
    ]
