# Generated by Django 4.1.7 on 2023-03-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service_app', '0010_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nuotrauka',
            field=models.ImageField(default='no_image.png', upload_to='profile_pics'),
        ),
    ]
